### ISSUE TITLE
Video Stream is not happening in ARDRONE

### ISSUE THREAD

**Issue by KathiravanNatarajan** [ros/ros#137]
Hi I am trying to get the video output of ARDRONE and process the images. 

I used the default code given by ROS. It's not displaying now. Where am I wrong here ? Launch file as well as my code is also perfect. 

This issue is not addressed including ROS answers and SO. Feeling so demotivated.
```

#!/usr/bin/env python
from __future__ import print_function
import roslib
import sys
import rospy
import cv2
from std_msgs.msg import String
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError
 


class image_converter:
 
  def __init__(self):
     self.image_pub = rospy.Publisher("image_topic_2",Image,queue_size=10)
   
     self.bridge = CvBridge()
     self.image_sub = rospy.Subscriber("image_topic",Image,self.callback)
   
  def callback(self,data):
     try:
       cv_image = self.bridge.imgmsg_to_cv2(data, "bgr8")
     except CvBridgeError as e:
       print(e)
      
     (rows,cols,channels) = cv_image.shape
     if cols > 60 and rows > 60 :
        cv2.circle(cv_image, (50,50), 10, 255)
   
     cv2.imshow("Image window", cv_image)
     cv2.waitKey(3)

def main(args):
    ic = image_converter()
    rospy.init_node('image_converter', anonymous=True)
    try:
      rospy.spin()
    except KeyboardInterrupt:
      print("Shutting down")
    cv2.destroyAllWindows()
  
if __name__ == '__main__':
    main(sys.argv)



```

Should I have to change any image topics here or what is the issue ? 
Please refer this for further info. http://answers.ros.org/question/252593/video-stream-needed-for-ardrone/

**Comment by dirk-thomas** [comment]
Since you have already asked your question on answers.ros.org please do not cross post the same question here. The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. Hopefully someone will answer your question there. If you get no response it could be nobody has the answer right away or that your questions doesn't contain enough information for others to make suggestions.
