### ISSUE TITLE
Catkin_make and scan-build

### ISSUE THREAD

**Issue by idzardh** [ros/ros#154]
Hi,

I have been trying to get scan-build of the clang toolchain to work with the ros build chain (catkin_make), to no succes, even going so far as to add bugs myself to see if it would work or not, however the scan-build system was not able to find any bugs in the source files of my project. Is there any reason why this would not work? I have also tried building it with only scan-build make but this also did not work. I think it would be a great addition to the build chain if this would work.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
