### ISSUE TITLE
Error install ROS on mac os

### ISSUE THREAD

**Issue by aalexren** [ros/ros#173]
After: 

> wstool init -j8 src kinetic-desktop-full-wet.rosinstall

ERROR in config: Error processing 'actionlib' : [actionlib] Checkout of https://github.com/ros-gbp/actionlib-release/archive/release/kinetic/actionlib/1.11.13-0.tar.gz version actionlib-release-release-kinetic-actionlib-1.11.13-0 into /Users/kot_mapku3/ros_catkin_ws/src/actionlib failed. Error processing 'angles' : [angles] Checkout of https://github.com/ros-gbp/geometry_angles_utils-release/archive/release/kinetic/angles/1.9.11-0.tar.gz version geometry_angles_utils-release-release-kinetic-angles-1.9.11-0 into /Users/kot_mapku3/ros_catkin_ws/src/angles failed. Error processing 'bond_core/bond' : [bond_core/bond] Checkout of https://github.com/ros-gbp/bond_core-release/archive/release/kinetic/bond/1.8.1-0.tar.gz version bond_core-release-release-kinetic-bond-1.8.1-0 into /Users/kot_mapku3/ros_catkin_ws/src/bond_core/bond failed. Error processing 'bond_core/bond_core' : [bond_core/bond_core] Checkout of https://github.com/ros-gbp/bond_core-release/archive/release/kinetic/bond_core/1.8.1-0.tar.gz version bond_core-release-release-kinetic-bond_core-1.8.1-0 into /Users/kot_mapku3/ros_catkin_ws/src/bond_core/bond_core failed. Error processing 'bond_core/bondcpp' : [bond_core/bondcpp] Checkout of https://github.com/ros-gbp/bond_core-release/archive/release/kinetic/bondcpp/1.8.1-0.tar.gz version bond_core-release-release-kinetic-bondcpp-1.8.1-0 into /Users/kot_mapku3/ros_catkin_ws/src/bond_core/bondcpp failed. Error processing 'bond_core/bondpy' : [bond_core/bondpy] Checkout of https://github.com/ros-gbp/bond_core-release/archive/release/kinetic/bondpy/1.8.1-0.tar.gz version bond_core-release-release-kinetic-bondpy-1.8.1-0 into /Users/kot_mapku3/ros_catkin_ws/src/bond_core/bondpy failed. Error processing 'bond_core/smclib' : [bond_core/smclib] Checkout of https://github.com/ros-gbp/bond_core-release/archive/release/kinetic/smclib/1.8.1-0.tar.gz version bond_core-release-release-kinetic-smclib-1.8.1-0 into /Users/kot_mapku3/ros_catkin_ws/src/bond_core/smclib failed. Error processing 'catkin' : [catkin] Checkout of https://github.com/ros-gbp/catkin-release/archive/release/kinetic/catkin/0.7.11-0.tar.gz version catkin-release-release-kinetic-catkin-0.7.11-0 into /Users/kot_mapku3/ros_catkin_ws/src/catkin failed.

What is this? I cannot install ros.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
