### ISSUE TITLE
Failed to install ROS on macOS

### ISSUE THREAD

**Issue by hongxinliu** [ros/ros#187]
I've followed procedures in this page: http://wiki.ros.org/kinetic/Installation/OSX/Homebrew/Source
Everything goes well before procedure 2.1.2. 
command in 2.1.2 "rosdep install --from-paths src --ignore-src --rosdistro kinetic -y" got following error: 

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
actionlib: No definition of [python-wxtools] for OS [osx]
roslisp: No definition of [google-mock] for OS [osx]
catkin: No definition of [google-mock] for OS [osx]

(Version of my macOS is 10.13.3)

**Comment by dirk-thomas** [comment]
This is not the right location to report that problem. The `rosdep` mappings are define in this repository: https://github.com/ros/rosdistro/tree/master/rosdep

Both `rosdep` keys don't have a mapping for `osx` defined at the moment:

* [google-mock](https://github.com/ros/rosdistro/blob/c02ca747c6d910b4e4526939627ef6e713dce964/rosdep/base.yaml#L992)
* [python-wxtools](https://github.com/ros/rosdistro/blob/c02ca747c6d910b4e4526939627ef6e713dce964/rosdep/python.yaml#L4278)

I can't say if that is intentional (since there is no "good" mapping to a package on OS) or just because nobody has contributed the entry until now.

Anyway since this is the wrong location I will go ahead and close this ticket. Please consider contributing the appropriate mappings via a pull request to the above referenced repository. If you do so please reference this ticket to cross-reference them so that future reads can find it.
