### ISSUE TITLE
rosbag: why use the Crypto package ?

### ISSUE THREAD

**Issue by CdeMills** [ros/ros#201]
Hello,
after installing and started the tutorials of "Melodic Morenia", I found the command "rostopic" failing at bag.py: 
from Crypto import Random
I have many issues with this approach:
1) the last release of pycrypto is from 2013
2) it has been superseeded by by cryptography
3) randomness should come from os.urandom(size) as explained on https://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/

What about replacing Random.new().read(AES.block_size) by os.urandom(AES.block_size) ?

Regards

Pascal

**Comment by dirk-thomas** [comment]
This ticket seems to be in the wrong place. Nothing in this repository uses `Crypto`. I assume you are referring to [ros_comm](https://github.com/ros/ros_comm/)?

> after installing and started the tutorials of "Melodic Morenia", I found the command "rostopic" failing at bag.py:
> from Crypto import Random

That sounds weird since the package declares a dependency on `python-crypto` which should be installed. So this shouldn't fail. Are you sure you installed all dependencies according to the instructions?

> I have many issues with this approach:

The use of `Crypto` was introduced recently in ros/ros_comm#1206. Please consider to provide a pull request to switch to a different implementation.

**Comment by tfoote** [comment]
@jwon02 FYI

**Comment by CdeMills** [comment]
Hello,

the target is an IoT type platform, so I need to determine "manually" which supplemental dependencies were required w.r.t the basic install.

I found that python-crypto latest release is in 2013; this lib has been superseded by python-cryptodome which implements the same API and add some new function. The latter should thus be the reference implementation for crypto functions.

Regards

Pascal

**Comment by dirk-thomas** [comment]
Moved to ros/ros_comm#1599.
