### ISSUE TITLE
[gazebo-1] process has died issue 

### ISSUE THREAD

**Issue by ahumay** [ros/ros#203]
Hi all, I am a complete novice to ROS so please be understanding. I searched extensively for duplicates of my issue.
I am just trying to make a map and navigate it in the Gazebo. I am running Ubuntu 15.10 and ROS Kinetic. I run these in separate terminal windows:

```
roslaunch turtlebot_gazebo turtlebot_world.launch

roslaunch turtlebot_gazebo gmapping_demo.launch

roslaunch turtlebot_rviz_launchers view_navigation.launch

roslaunch kobuki_keyop keyop.launch

```
But I my kobuki_keyop does not work, giving me:
```

[ WARN] [1550005269.894992827]: KeyOp: could not connect, trying again after 500ms...
[ERROR] [1550005270.400225747]: KeyOp: could not connect.
[ERROR] [1550005270.400604286]: KeyOp: check remappings for enable/disable topics).

```
I then check the roslaunch turtlebot_gazebo turtlebot_world.launch terminal window, and see the following error:
```
[gazebo-1] process has died [pid 5190, exit code 134, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /opt/ros/kinetic/share/turtlebot_gazebo/worlds/playground.world __name:=gazebo __log:=/home/tony15/.ros/log/534c6c66-2ef1-11e9-854a-080027d85737/gazebo-1.log].
log file: /home/tony15/.ros/log/534c6c66-2ef1-11e9-854a-080027d85737/gazebo-1*.log
Upon further inspection, it seems that if I roslaunch turtlebot_gazebo turtlebot_world.launch, then as soon as I roslaunch turtlebot_gazebo gmapping_demo.launch, the turtlebot_world.launch receives the previous error (which then explains why the kobuki_keyop doesn't work).

```
turtlebot_world.launch works completely fine on it's own.

turtlebot_world.launch and kobuki_keyop work fine when both running.

Does anyone know why my turtlebot_world.launch and gmapping_demo.launch / turtlebot_rviz_launchers can't seem to run at the same time? Is it related to multiple turtlebot_gazebo instances running?

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
