### ISSUE TITLE
Clock node not published

### ISSUE THREAD

**Issue by woongjoonchoi** [ros/ros#230]
I launch rospackage.
Then , i check the rostopic info

BUt, clock node is something wrong  

oongjoon@oongjoon-VivoBook-ASUSLaptop-X512DA-R564DA:~$ rostopic info /clock 
Type: rosgraph_msgs/Clock

Publishers: None

Subscribers: 
 * /rosout (http://oongjoon-VivoBook-ASUSLaptop-X512DA-R564DA:42771/)
 * /tf_depth_camera (http://oongjoon-VivoBook-ASUSLaptop-X512DA-R564DA:38145/)
 * /mavros (http://oongjoon-VivoBook-ASUSLaptop-X512DA-R564DA:38255/)
 * /local_planner_node (http://oongjoon-VivoBook-ASUSLaptop-X512DA-R564DA:36619/)
 * /standalone_nodelet (http://oongjoon-VivoBook-ASUSLaptop-X512DA-R564DA:41145/)
 * /convert_metric (http://oongjoon-VivoBook-ASUSLaptop-X512DA-R564DA:44071/)
 * /points_xyz (http://oongjoon-VivoBook-ASUSLaptop-X512DA-R564DA:45177/)
 * /rviz (http://oongjoon-VivoBook-ASUSLaptop-X512DA-R564DA:42997/)
 * /spawn_model (http://oongjoon-VivoBook-ASUSLaptop-X512DA-R564DA:36537/)
 * /rqt_reconfigure (http://oongjoon-VivoBook-ASUSLaptop-X512DA-R564DA:41557/)

i think that publisher must not be none.
But , idont know why. what shuold ido?

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
