### ISSUE TITLE
'Could not find a package configuration file provided by "message_runtime"' during `catkin build`

### ISSUE THREAD

**Issue by iwishiwasaneagle** [ros/ros#263]
Whilst running `catkin build` I receive the following CMake error:

```
Errors     << mavros_msgs:cmake /home/vagrant/catkin_ws/logs/mavros_msgs/build.cmake.005.log                                                                                                                        
CMake Error at /opt/ros/melodic/share/geographic_msgs/cmake/geographic_msgsConfig.cmake:197 (find_package):
  Could not find a package configuration file provided by "message_runtime"
  with any of the following names:

    message_runtimeConfig.cmake
    message_runtime-config.cmake

  Add the installation prefix of "message_runtime" to CMAKE_PREFIX_PATH or
  set "message_runtime_DIR" to a directory containing one of the above files.
  If "message_runtime" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  CMakeLists.txt:4 (find_package)
```
Running the following also hasn't helped:
`CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH:/opt/ros/melodic/share" catkin build`
`sudo apt-get install ros-melodic-message-runtime`

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
