### ISSUE TITLE
where do I find missed packages in source form?

### ISSUE THREAD

**Issue by AndreV84** [ros/ros#271]
```
~/ros_catkin_ws$  rosdep install --from-paths ./src --ignore-packages-from-source --rosdistro noetic -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
xarm7_moveit_config: No definition of [moveit_ros_visualization] for OS version [bionic]
xarm5_gripper_moveit_config: No definition of [moveit_setup_assistant] for OS version [bionic]
xarm5_moveit_config: No definition of [moveit_setup_assistant] for OS version [bionic]

dual_xarm6_moveit_config: No definition of [moveit_setup_assistant] for OS version [bionic]
xarm_controller: No definition of [control_toolbox] for OS version [bionic]
realsense2_camera: Cannot locate rosdep definition for [ament_lint_common]
tf_conversions: [python3-pykdl] defined as "not available" for OS version [bionic]
xarm6_moveit_config: No definition of [moveit_setup_assistant] for OS version [bionic]
xarm7_gripper_moveit_config: No definition of [moveit_setup_assistant] for OS version [bionic]
tf2_geometry_msgs: [python3-pykdl] defined as "not available" for OS version [bionic]
xarm6_gripper_moveit_config: No definition of [moveit_setup_assistant] for OS version [bionic]
xarm_planner: Cannot locate rosdep definition for [moveit_visual_tools]
```
I built noetic from source at arm device with ubuntu bionic 18.04

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
