### ISSUE TITLE
Why do we use pipe when we communicate with IPC？

### ISSUE THREAD

**Issue by zijian1998** [ros/ros#276]
I am studying the code of ROS(kinetic),but when I read the io.cpp. I was confused about the way we used.
In the ~/src/ros_comm/roscpp/src/libros/io.cpp line 508，we used the pipe to help us communicate.
But do we have the parent child process?
```
#else // use a pipe pair
	// initialize
	signal_pair[0] = -1;
	signal_pair[1] = -1;

	if(pipe(signal_pair) != 0) {
		ROS_FATAL( "pipe() failed");
		return -1;
	}
	if(fcntl(signal_pair[0], F_SETFL, O_NONBLOCK) == -1) {
		ROS_FATAL( "fcntl() failed");
		return -1;
	}
	if(fcntl(signal_pair[1], F_SETFL, O_NONBLOCK) == -1) {
		ROS_FATAL( "fcntl() failed");
		return -1;
	}
	return 0;
#endif // create_pipe
```

**Comment by hidmic** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support), but we kindly ask to raise questions like this on answers.ros.org instead.

The rationale for asking these sort of questions in a single place is:

- There are many more people reading questions there, so your chances on getting an answer in a timely manner are much higher.
- In the future, other users will search there for similar problems and can find your question and the potential answers.
- The issue tracker in this repository is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore, I will close this ticket here for now. If you have asked your question on answers.ros.org, please feel free to add a link to the question to this ticket so that future readers can find the related question. We may be able to reply it if you do.
