### ISSUE TITLE
roslib: Python call in hook

### ISSUE THREAD

**Issue by bchretien** [ros/ros#55]
On Arch Linux, the default Python version is Python 3, and we currently use Python 2 for ROS Groovy/Hydro. I recently had to patch the hook in `roslib` since it relies on `python` calls:

``` sh
# scrub old ROS bin dirs, to avoid accidentally finding the wrong executables
export PATH="`python -c \"import os; print(os.pathsep.join([x for x in \\\"$PATH\\\".split(os.pathsep) if not any([d for d in ['cturtle', 'diamondback', 'electric', 'fuerte'] if d in x])]))\"`"
...
export ROS_PACKAGE_PATH="`python -c \"$PYTHON_CODE_BUILD_ROS_PACKAGE_PATH\"`"
```

Indeed, on a fresh Arch install, Python 2 will be installed by the package manager when dealing with dependencies (since we rely on it), but `python` (i.e. Python 3's `/usr/bin/python`) might not be, as reported by an Arch user [here](https://aur.archlinux.org/packages/ros-hydro-rosmake/). It took me a while to detect that since I added a symlink `~/bin/python ---> /usr/bin/python2`, but this kind of things may happen on other Linux distributions as well.

I guess adding `CATKIN_PYTHON_EXECUTABLE` (or any other more suitable name) to catkin's `/opt/ros/hydro/share/catkin/cmake/templates/env-hook.context.py.in` could solve this.

**Comment by dirk-thomas** [comment]
You might want to use _Indigo_ instead of of _Groovy_ / _Hydro_ since many Python 3 related issues have been addressed since then. Neither _Groovy_ nor _Hydro_ will be patched to improve Python 3 support.

This specific problem is still present in _Indigo_ though.

**Comment by bchretien** [comment]
Well, some people may need to stick with groovy/hydro (when you share code with colleagues stuck on old Ubuntu LTS), so this is still worth fixing. Nonetheless, thanks for the patch!

**Comment by dirk-thomas** [comment]
The amount of code changes for supporting Python 3 is enormous. Backporting them to Groovy/Hydro would not only be a huge effort but would very likely break stuff and is therefore not feasible for ROS distros which have been released such a long time ago and are expected to be stable.

**Comment by bchretien** [comment]
Here this is not about backporting at all. It's quite the contrary. This code assumed that `python == python2`, which is wrong on some distributions like Arch Linux. We use Python 2 for Groovy/Hydro and this is not going to change. But the hook needed to be fixed in order to use Python 2 for Groovy/Hydro.

**Comment by dirk-thomas** [comment]
The problem is that Arch is the only platform not following PEP 394 (http://legacy.python.org/dev/peps/pep-0394/).

Currently the fix only went to the _indigo-devel_ branch and would therefore effect neither Groovy nor Hydro. It would need to be backported (as well as the dependent patch in `catkin`) to effect them.

I am pretty sure that there are numerous other locations in the source code which will stumble upon that difference. Some Python code in Groovy and Hydro will not even pass as valid Python 3 code.

Have you built, ran and tested significant parts of ROS (e.g. desktop) on Arch and everything works without patching when `python` points to a Python 3 interpreter? And this environment hook is the only problem right now?

**Comment by bchretien** [comment]
I successfully packaged around [660 Hydro packages](https://aur.archlinux.org/packages/?O=0&K=ros-hydro) on Arch with Python 2. We automatically `sed` shebangs to ensure that Python 2 is used, so all the Python code I packaged works. Here, this issue concerns the core of ROS, which is why I decided to report this, since this may concern other distributions at some point. I missed it at first since this is not in a Python script (thus not checked automatically), and also because I use `~/bin/python` that points to `/usr/bin/python2` (but most people don't).

As for whether Linux distributions should move to Python 3 as the default Python version, this is a recurrent issue (kind of like C++11 support). Personally, I think that after over 5 years, it is time to move on... Even PEP 394 was made over 3 years ago! Arch Linux may have moved to Python 3 too early (2010-10-18), but now, the other distributions need to follow (Ubuntu 14.04 is certainly going to be a strong motivator), even if it is painful. Arch showed that it is possible, after all. Plus, having a rolling release that promotes the use of Python 2 would be a bit preposterous :-)

Finally, since Python 3 support is added in Indigo, I will move on to Python 3 when packaging it on Arch. I actually just received a mail from an Arch user asking about Indigo packages, so I'll try to test it in the coming weeks.

**Comment by dirk-thomas** [comment]
Thanks for clarifying - that helps to understand how you currently build/use ROS on Arch.

I would propose that you continue to apply the custom patch to the environment hook for your Groovy and Hydro builds. But for Indigo we should aim for not requiring any patches - if you face any cases where you need to patch it please fill a ticket about it and we will address it since we want to support Python 3 (even if we don't build for it by default).
