### ISSUE TITLE
`rosboost-cfg --lflags thread` fails on standard ubuntu 14.04

### ISSUE THREAD

**Issue by v4hn** [ros/ros#66]
This problem is already known and was more or less repaired within rosbuild by https://github.com/ros/ros/pull/63.

However, this commit still doesn't repair the simple and well-established
command line `rosboost-cfg --lflags thread` that is used in older manifest.xml files to export cflags.

```
$ rosboost-cfg --ldflags thread
Usage: rosboost-cfg [options]

rosboost-cfg: error: no such option: --ldflags
robot@robot10:~/ros/indigo/muffin-dry/mobman/calvin_navigation$ rosboost-cfg --lflags thread
Traceback (most recent call last):
  File "/opt/ros/indigo/bin/rosboost-cfg", line 35, in <module>
    rosboost_cfg.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosboost_cfg/rosboost_cfg.py", line 362, in main
    output = lflags(ver, options.lflags.split(','))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosboost_cfg/rosboost_cfg.py", line 280, in lflags
    s += lib_flags(ver, lib) + " "
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosboost_cfg/rosboost_cfg.py", line 270, in lib_flags
    lib = find_lib(ver, name)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosboost_cfg/rosboost_cfg.py", line 240, in find_lib
    raise BoostError('Could not locate library [%s], version %s'%(name, ver))
rosboost_cfg.rosboost_cfg.BoostError: "Could not locate library [thread], version (1, 54, 0, '/usr', '/usr/include', True, True)"
```

**Comment by wjwwood** [comment]
@dirk-thomas this was reported from IRC, I told him to open it here.

**Comment by wjwwood** [comment]
Also, I can reproduce it on my 14.04 VM.

**Comment by dirk-thomas** [comment]
The correct invocation in 14.04 is:

```
rosboost-cfg --multiarch=YOURARCH --lflags thread
```

`YOURARCH` can be detected with either of these commands:

```
gcc -print-multiarch
dpkg-architecture -qDEB_HOST_MULTIARCH
```

**Comment by v4hn** [comment]
Sure, but then why don't you simply add this architecture detection to the rosboost-cfg
utility? That way the old usage would still work just fine and there's no need to
change old manifest files. Imho this breaks APIs for no real reason or value.

**Comment by dirk-thomas** [comment]
To clarify: the `API break` was introduced in Boost by placing the libraries into a different location. We did not change anything in `rosboost-cfg`. This is basically the cost of keeping existing code working with newer versions of other stuff.

It would be possible to patch `rosboost-cfg` to automaticallly determine the `multiarch` argument if the lookup without it was unsuccessful and try to resolve the query again using that multiarch value. (This will imply additional external command invocations and implicit dependencies on either of the called tools.)

Please consider to provide a pull request to add this new feature since I might not have time to work on this in the near future.

**Comment by v4hn** [comment]
rosbuild is obsolete, so closing the request
