### ISSUE TITLE
dh_auto_test/rosbuild issue

### ISSUE THREAD

**Issue by NicoVT** [ros/ros#71]
I have experienced an issue on Ubuntu 14.04/Indigo with dh_auto_test and rosbuild.
At the end of the dh_auto_test step, a clean test result is done by calling a file build.make like this: CMakeFiles/rosbuild_clean-test-results.dir/build. This build.make generate this error: 
make[4]: Entering directory `/var/lib/jenkins/workspace/........./obj-x86_64-linux-gnu'
if ! rm -rf /home/xxxx/.ros/test_results/xxxx; then echo "WARNING:\ failed\ to\ remove\ test-results\ directory"\; fi
/bin/sh: 1: Syntax error: end of file unexpected (expecting "fi")

If you look at the error, you can see that after "directory" there is a "\". This "\" need to be removed. I found that build.make is generated from a ros cmake file: "/opt/ros/indigo/share/ros/core/rosbuild/public.cmake". So, in order to fix this issue, you need to modify the line 365 of /opt/ros/indigo/share/ros/core/rosbuild/public.cmake by replacing directory"\ by directory".

I know that rosbuild is not the recommended build for ROS but could you fix this issue in the next release?

**Comment by tfoote** [comment]
That looks to have changed for newer versions of cmake [change](https://github.com/ros/ros/commit/a1560041dcf7b33960a9250dafce120b409dc801) 

That backslash escapes the `"` symbol so that it doesn't get interpreted on that line. You'll note there are several more `\`s in that direct string. Something else is trying to escape the strings incorrectly. That `\` is not the correct fix. [line](https://github.com/ros/ros/blob/indigo-devel/core/rosbuild/core/rosbuild/public.cmake#L364)

Can you provide a simple test to reproduce your failure outside your debian build process (aka a few commands in an example package)?

I'm not sure how you're trying to use dh_auto_test, to build rosbuild packages into debian packages, but there are a lot more fundamental issues with using rosbuild to build debian packages than just escaping lines correctly. Most of it will likely still work, but in general we'll review pull-requests which won't break other use cases but will not spend time debugging or developing on rosbuild. 

For reference: If you'd like to see what we have supported through groovy, [single_deb.py](https://github.com/ros-infrastructure/buildfarm/blob/master/scripts/single_deb.py) ran the latest generation of the full build. And [generate_sourcedeb](https://github.com/ros-infrastructure/buildfarm/blob/master/scripts/generate_sourcedeb)

**Comment by NicoVT** [comment]
Sorry I copied the output of the command. So the right fix (for /opt/ros/indigo/share/ros/core/rosbuild/public.cmake line 365) is:
before: 
if ! rm -rf ${rosbuild_test_results_dir}/${PROJECT_NAME}\; then echo "\"WARNING: failed to remove test-results directory\"\;" fi)

now: 
if ! rm -rf ${rosbuild_test_results_dir}/${PROJECT_NAME}\; then echo "\"WARNING: failed to remove test-results directory\";" fi)

I have tested this modification on Ubuntu 12.04/fuerte/cmake version 2.8.7 and Ubuntu 14.04/Indigo/cmake version 2.8.12.2. For both system that works. Just to let you know, I had no problem on Ubuntu 12.04/fuerte but I just would like to see if the modification works on this system.

**Comment by dirk-thomas** [comment]
Can you please provide a command sequence which can be run to reproduce the issue as well as confirm that your proposed fix addresses the problem?
