### ISSUE TITLE
Missing #!/usr/bin/env python in the roscreatepkg.py file

### ISSUE THREAD

**Issue by lepalom** [ros/ros#79]
This package install a script that does not start with the #! sequence that marks interpreted scripts.

**Comment by dirk-thomas** [comment]
The file you refer to (https://github.com/ros/ros/blob/c6e91f9af1410ef183cfa273a7395f896d2d2a1f/tools/roscreate/src/roscreate/roscreatepkg.py) is a Python module. It does not have and should not have a shebang line. It also does not have the executable bit set since it should not be invoked directly.

The script you want to invoke instead is: https://github.com/ros/ros/blob/c6e91f9af1410ef183cfa273a7395f896d2d2a1f/tools/roscreate/scripts/roscreate-pkg
